language: node_js
node_js:
  - "4"  # LTS   from 2015-10 maintenance till 2018-04
  - "6"  # LTS   from 2016-10 maintenance till 2019-04
#  - "7"  # devel from 2016-10
#  - "8"  # LTS   from 2017-10 maintenance till 2019-12
#  - "9"  # devel from 2017-10
script: "npm run-script test-travis"

services:
  - mongodb

# coveralls integration
#after_success:
#  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=kdLeun9GUXgeiLjRUk8Dos8VL3hkYafyv node_modules/.bin/builder test --coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

# Fix the c++ compiler on Ubuntu 14.04
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
